### PR TITLE
Revert "First draft of docker file"

### PR DESCRIPTION
**Pull request by abedford**
Reverts abedford/DevOps-Course-Starter#7

### CODE REVIEW

**Comment by abedford** [comment]
Hi, have made changes to get the tests working in docker. The test containers builds and runs, but there are couple of test failures. Can I merge this branch in at this point and look at the failing tests as part of the next module?

**Comment by abedford** [comment]
Also see https://github.com/abedford/DevOps-Course-Starter/pull/10 for the final fix for this module.

**Comment by hugh-emerson** [comment]
This PR undoes your module 5 work. Why would you want to merge this?

**Comment by abedford** [comment]
Argh, I got a bit confused I think as I merged first, then thought I probably needed to wait for one of you to approve it so tried reverting it but it didn't quite do what I expected. What's the best way to get everything to the right place?

**Pull request closed without merging**
